version: '3.8'

services:
  db:
    image: postgres:15
    container_name: search_hotel_postgres
    restart: always
    environment:
      POSTGRES_DB: search_hotel_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
