---
grails:
    profile: web
    codegen:
        defaultPackage: search.hotel
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none
management:
    endpoints:
        jmx:
            unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
    username: user  # замените на ваше имя пользователя
    password: password  # замените на ваш пароль
    dbCreate: update # create, create-drop, update, none
    properties:  # Добавьте этот блок для SSL
        jdbcUrl: jdbc:postgresql://rc1a-sqbvonth8em7um25.mdb.yandexcloud.net:6432/search_hotel_db
        connectionInitSql: "SELECT version();"
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        validationQuery: "SELECT 1"
        testOnBorrow: true
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 60000
        removeAbandoned: true
        removeAbandonedTimeout: 300
        logAbandoned: true
        jdbcInterceptors: "ConnectionState;StatementCache(max=200)"
        jdbcProperties:  # SSL параметры
            ssl: "true"
            sslmode: "verify-full"
            sslrootcert: "/home/appuser/.postgresql/root.crt"

environments:
    development:
        dataSource:
            url: jdbc:postgresql://rc1a-sqbvonth8em7um25.mdb.yandexcloud.net:6432/search_hotel_db?ssl=true&sslmode=verify-full&sslrootcert=/home/appuser/.postgresql/root.crt
            username: user  # замените на ваше имя пользователя
            password: password  # замените на ваш пароль
    test:
        dataSource:
            url: jdbc:postgresql://rc1a-sqbvonth8em7um25.mdb.yandexcloud.net:6432/search_hotel_db_test?ssl=true&sslmode=verify-full&sslrootcert=/home/appuser/.postgresql/root.crt
            username: user  # замените на ваше имя пользователя
            password: password  # замените на ваш пароль
    production:
        dataSource:
            url: jdbc:postgresql://rc1a-sqbvonth8em7um25.mdb.yandexcloud.net:6432/search_hotel_db_prod?ssl=true&sslmode=verify-full&sslrootcert=/home/appuser/.postgresql/root.crt
            username: user  # замените на ваше имя пользователя
            password: password  # замените на ваш пароль